### ISSUE TITLE
ERROR: Service 'iris' failed to build : Build failed

### ISSUE THREAD

**Issue by mwaseem75** [grongierisc/interoperability-embedded-python#1]
Hi,

I am getting below docker error

failed to solve with frontend dockerfile.v0: failed to create LLB definition: containers.intersystems.com/intersystems/iris-community:2021.2.0.617.0: not found

Thanks

**Comment by eduard93** [comment]
Try with `containers.intersystems.com/intersystems/iris-community:2021.2.0.649.0`

**Comment by grongierisc** [comment]
Iris version bumped to : ARG IMAGE=containers.intersystems.com/intersystems/irishealth-community:2021.2.0.651.0
