### ISSUE TITLE
iop not found

### ISSUE THREAD

**Issue by evshvarov** [grongierisc/interoperability-embedded-python#13]
While building a docker image

**Comment by grongierisc** [comment]
Hi for now, this repo is not suppose to be for build or demo, this is the core source code.
For demo, use this repo : https://github.com/grongierisc/iris-python-interoperability-template

Never the less, this is still an issue, and i will fixe it in the next days

**Comment by evshvarov** [comment]
I see! Thank you, @grongierisc
